name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  font_inspire_twdc:
    hosted: 'https://dispub.latest.disney.io'
    version: '^3.0.0'
  hyperion_components:
    hosted: 'https://dispub.latest.disney.io'
    version: '^8.6.5'
  flutter_inappwebview: ^6.1.5
  go_router: ^14.6.3
  provider: ^6.1.2
  riverpod: ^2.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
